server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

      default-filters:
        - PreserveHostHeader

      routes:
        - id: usuarios
          uri: lb://msv-usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2

        - id: roles
          uri: lb://msv-roles
          predicates:
            - Path=/api/roles/**
          filters:
            - StripPrefix=2

    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: INFO
