server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - PreserveHostHeader
          routes:
            - id: usuarios
              uri: lb://msv-usuarios
              predicates:
                - Path=/api/usuarios/**
              filters:
                - StripPrefix=2
            - id: roles
              uri: lb://msv-roles
              predicates:
                - Path=/api/roles/**
              filters:
                - StripPrefix=2
            - id: huespedes
              uri: lb://msv-huespedes
              predicates:
                - Path=/api/huespedes/**
              filters:
                - StripPrefix=2
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              "[/**]":
                allowed-origins:
                  - http://localhost:4200
                  - http://localhost:5173
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: ["*"]
                allow-credentials: true
                max-age: 3600

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,gatewayserver
  endpoint:
    gateway:
      enabled: true
    gatewayserver:
      enabled: true
