server:
  port: 8083

spring:
  application:
    name: msv-huespedes

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    appname: msv-huespedes
    instance-id: ${spring.application.name}:${server.port}

    # FORZAR QUE EUREKA USE IP, NO EL HOSTNAME "comunes"
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    non-secure-port: ${server.port}
    home-page-url: http://127.0.0.1:${server.port}/
    status-page-url: http://127.0.0.1:${server.port}/actuator/info
    health-check-url: http://127.0.0.1:${server.port}/actuator/health

    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
